### ISSUE TITLE
InheritedWidget pattern

### ISSUE THREAD

**Issue by sugitlab** [sugitlab/flutter_state_management_encyclopedia#2]
```yaml
start_date: 2021/6/29
due_date: 2021/6/29
progress: 0
parent: 0
dependon:
  - '5'
```
https://flutter.dev/docs/development/data-and-backend/state-mgmt/options#inheritedwidget--inheritedmodel
