### ISSUE TITLE
test

### ISSUE THREAD

**Issue by sugitlab** [sugitlab/flutter_state_management_encyclopedia#5]
```yaml
start_date: 2021/7/5
due_date: 2021/7/18
progress: 0.37
parent: 0
```
